// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2fq96hHD22GhnsZzKNycvgUqk7ZB_qfA',
    appId: '1:428334466853:web:20482ce53a74f6e962fccc',
    messagingSenderId: '428334466853',
    projectId: 'boletero-1e0d6',
    authDomain: 'boletero-1e0d6.firebaseapp.com',
    storageBucket: 'boletero-1e0d6.appspot.com',
    measurementId: 'G-0V6CCYE11B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWPpna2yj1pho6G3Mm9pPl0PRjGBB_MTQ',
    appId: '1:428334466853:android:ac7561478646224e62fccc',
    messagingSenderId: '428334466853',
    projectId: 'boletero-1e0d6',
    storageBucket: 'boletero-1e0d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv69OVvd73ZsevSS9JPaMwPgwPLzYt5us',
    appId: '1:428334466853:ios:0e890d119a08d12962fccc',
    messagingSenderId: '428334466853',
    projectId: 'boletero-1e0d6',
    storageBucket: 'boletero-1e0d6.appspot.com',
    iosClientId: '428334466853-gmiarf27pflht5qh6et2aa0rb750uaet.apps.googleusercontent.com',
    iosBundleId: 'com.example.boletero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv69OVvd73ZsevSS9JPaMwPgwPLzYt5us',
    appId: '1:428334466853:ios:981c7bf5b59b179b62fccc',
    messagingSenderId: '428334466853',
    projectId: 'boletero-1e0d6',
    storageBucket: 'boletero-1e0d6.appspot.com',
    iosClientId: '428334466853-s5fnsong2ar370ibrrklob396mbqkfnj.apps.googleusercontent.com',
    iosBundleId: 'com.example.boletero.RunnerTests',
  );
}
